### ISSUE TITLE
[BUG] Sugargoo links from taobao not opening

### ISSUE THREAD

**Issue by desoft5** [cachho/reparchive-browser-extension#83]
There is an "html" in the taobao links where there should only be an "htm".
Video explanation: https://imgur.com/a/31bGc74

I don't know if this is just a problem with sugargoo (it might be)
But if this could be fixed that would be great.

**Comment by cachho** [comment]
Hey, thanks for opening this issue. I'm investigating. could it be that the link is just dead?

This link works, and it also only has `htm` without the `l`. 

https://www.sugargoo.com/#/home/productDetail?productLink=https%3A%2F%2Fitem.taobao.com%2Fitem.htm%3Fid%3D693877066284

Taobao also sees `https://item.taobao.com/item.htm?id=693877066284` as a valid link.

**Comment by cachho** [comment]
Ok I see now that the bug is the other way around.

**Comment by cachho** [comment]
should be fixed in the current version. Let's wait until it hits the shelf.

**Comment by cachho** [comment]
looks fixed, thanks again for reporting. closing this issue.
